sudo: false
language: python
python:
  - "2.7"
#  - "3.4"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
virtualenv:
  system_site_packages: true
install:
  - pip install .
# command to run tests, e.g. python setup.py test
script: 
  - flake8 .
