sudo: false
notifications:
  irc:
    channels: "chat.freenode.net#firedrake"
    skip_join: true
    on_success: change
    on_failure: always
    template: "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} | %{build_url}"
language: python
addons:
  apt:
    packages:
        - libblas-dev
        - liblapack-dev
        - python-scipy
python:
#  - "3.3"
  - "2.7"
#  - "2.6"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
virtualenv:
  system_site_packages: true
install:
  - pip install git+https://github.com/firedrakeproject/fiat.git#egg=fiat 
  - pip install -r requirements.txt
  - pip install pytest-pep8
# command to run tests, e.g. python setup.py test
script: 
  - export PYTHONPATH=`pwd`:$PYTHONPATH
  - make test
