sudo: false

language: python
python:
  - "3.5"

before_install:
  - pip install -r requirements.txt
  - pip install flake8

install:
  - python setup.py install

script:
  - flake8 .
  - py.test test
